#!/usr/bin/python
import cgi
import cgitb; cgitb.enable()
import cgitb; cgitb.enable(display=0, logdir="/tmp")

form= cgi.FieldStorage()

def configure():
    #...............
    header= """Content-type: text/html

    <title>TTU Configuration Interface</title>
    <head>
    <style type="text/css">
    """
    #...............
    cssfile = open('ttu_style.css','r')
    #...............
    print header
    print cssfile.read()
    print '</style>'
    #...............

    print '<html>'
    print '<body>'
    print ''
    #...
    print ''
    print '<div id="TopTitle">'
    print '<h1>RPC - Technical Trigger Configuration</h1>'
    print '<p class="top" >'
    print '<a class="top" href="http://www.cern.ch" target="_blank">Wiki-Doc</a>'
    print '<a class="top" href="mailto:aosorio@NOTSPAM.uniandes.edu.co">Contact</a> v.1.0'
    print '</p>'
    print '</div>'
    print ''
    #...
    print '<div id="Content">'
    print '<h3>TTU Configuration</h3>'

    print '<h4>'
    print 'Selected Preset: %s' % form['Presets'].value
    print '</h4>'

    #...
    print ''
    print '<h4>TTU: Wheel -2</h4>'
    print ''
    print '<form name="mainform" action="http://localhost:5000/configure.exec-cgi.py">'
    print ''
    print '<p>'
    print '  Logic Type:'
    print '  <select name="TriggerMode.W-2">'
    print '    <option value="LocalOR">Local (RBC) OR</option>'
    print '    <option value="GlobalOR">Global (Wheel) OR</option>'
    print '    <option value="CombinedOR">Combined (RBC+Wheel)  OR</option>'
    print '  </select>'
    print '</p>'
    print ''
    print '<p>'
    print '  Delay/Latency:'
    print '  <input type="text" name="Delay.W-2" />'
    print '</p>'
    print ''
    print '<p>'
    print '  Track length:'
    print '  <input type="text" name="TrkLen.W-2" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Mask:'
    print '<input type="checkbox" name="masks" value="MaskIn.W-2" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Force:'
    print '<input type="checkbox" name="force" value="ForceIn.W-2" />'
    print '</p>'
    print ''
    print ''
    print '<h4>TTU: Wheel -1</h4>'
    print ''
    print ''
    print '<p>'
    print '  Logic Type:'
    print '  <select name="TriggerMode.W-1">'
    print '    <option value="LocalOR">Local (RBC) OR</option>'
    print '    <option value="GlobalOR">Global (Wheel) OR</option>'
    print '    <option value="CombinedOR">Combined (RBC+Wheel)  OR</option>'
    print '  </select>'
    print '</p>'
    print ''
    print '<p>'
    print '  Delay/Latency:'
    print '  <input type="text" name="Delay.W-1" />'
    print '</p>'
    print ''
    print '<p>'
    print '  Track length:'
    print '  <input type="text" name="TrkLen.W-1" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Mask:'
    print '<input type="checkbox" name="masks" value="MaskIn.W-1" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Force:'
    print '<input type="checkbox" name="force" value="ForceIn.W-1" />'
    print '</p>'
    print ''
    print ''
    print ''
    print '<h4>TTU: Wheel 0</h4>'
    print ''
    print ''
    print '<p>'
    print '  Logic Type:'
    print '  <select name="TriggerMode.W0">'
    print '    <option value="LocalOR">Local (RBC) OR</option>'
    print '    <option value="GlobalOR">Global (Wheel) OR</option>'
    print '    <option value="CombinedOR">Combined (RBC+Wheel)  OR</option>'
    print '  </select>'
    print '</p>'
    print ''
    print '<p>'
    print '  Delay/Latency:'
    print '  <input type="text" name="Delay.W0" />'
    print '</p>'
    print ''
    print '<p>'
    print '  Track length:'
    print '  <input type="text" name="TrkLen.W0" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Mask:'
    print '<input type="checkbox" name="masks" value="MaskIn.W0" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Force:'
    print '<input type="checkbox" name="force" value="ForceIn.W0" />'
    print '</p>'
    print ''
    print '<h4>TTU: Wheel +1</h4>'
    print ''
    print ''
    print '<p>'
    print '  Logic Type:'
    print '  <select name="TriggerMode.W+1">'
    print '    <option value="LocalOR">Local (RBC) OR</option>'
    print '    <option value="GlobalOR">Global (Wheel) OR</option>'
    print '    <option value="CombinedOR">Combined (RBC+Wheel)  OR</option>'
    print '  </select>'
    print '</p>'
    print ''
    print '<p>'
    print '  Delay/Latency:'
    print '  <input type="text" name="Delay.W+1" />'
    print '</p>'
    print ''
    print '<p>'
    print '  Track length:'
    print '  <input type="text" name="TrkLen.W+1" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Mask:'
    print '<input type="checkbox" name="masks" value="MaskIn.W+1" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Force:'
    print '<input type="checkbox" name="force" value="ForceIn.W+1" />'
    print '</p>'
    print ''
    print '<h4>TTU: Wheel +2</h4>'
    print ''
    print ''
    print '<p>'
    print '  Logic Type:'
    print '  <select name="TriggerMode.W+2">'
    print '    <option value="LocalOR">Local (RBC) OR</option>'
    print '    <option value="GlobalOR">Global (Wheel) OR</option>'
    print '    <option value="CombinedOR">Combined (RBC+Wheel)  OR</option>'
    print '  </select>'
    print '</p>'
    print ''
    print '<p>'
    print '  Delay/Latency:'
    print '  <input type="text" name="Delay.W+2" />'
    print '</p>'
    print ''
    print '<p>'
    print '  Track length:'
    print '  <input type="text" name="TrkLen.W+2" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Mask:'
    print '<input type="checkbox" name="masks" value="MaskIn.W+2" />'
    print '</p>'
    print ''
    print '<p>'
    print 'Force:'
    print '<input type="checkbox" name="force" value="ForceIn.W+2" />'
    print '</p>'
    print ''
    print '<input type=submit value="Execute" />'
    print '</form>'

    #.RBC configurations..............................
    print '<h4>Wheel -2: RBC Configuration</h4>'
    print ''
    print '<p>'
    print 'Select RBC board to configure:'
    print ''
    print '<form name="secform" action="http://localhost:5000/configure.rbc-cgi.py">'
    print '<select name="RBCboard">'
    print '    <option value="RBC.1.1">RBC:12-1</option>'
    print '    <option value="RBC.1.2">RBC:2-3</option>'
    print '    <option value="RBC.1.3">RBC:4-5</option>'
    print '    <option value="RBC.1.4">RBC:6-7</option>'
    print '    <option value="RBC.1.5">RBC:8-9</option>'
    print '    <option value="RBC.1.6">RBC:10-11</option>'
    print '</select>'
    print '<input type=submit value="Configure" />'
    print '</p>'
    print '</form>'
    print ''

    print '<h4>Wheel -1: RBC Configuration</h4>'
    print ''
    print '<p>'
    print 'Select RBC board to configure:'
    print ''
    print '<form name="secform" action="http://localhost:5000/configure.rbc-cgi.py">'
    print '<select name="RBCboard">'
    print '    <option value="RBC.3.1">RBC:12-1</option>'
    print '    <option value="RBC.3.2">RBC:2-3</option>'
    print '    <option value="RBC.3.3">RBC:4-5</option>'
    print '    <option value="RBC.3.4">RBC:6-7</option>'
    print '    <option value="RBC.3.5">RBC:8-9</option>'
    print '    <option value="RBC.3.6">RBC:10-11</option>'
    print '</select>'
    print '<input type=submit value="Configure" />'
    print '</p>'
    print '</form>'
    print ''

    print '<h4>Wheel 0:RBC Configuration</h4>'
    print ''
    print '<p>'
    print 'Select RBC board to configure:'
    print ''
    print '<form name="secform" action="http://localhost:5000/configure.rbc-cgi.py">'
    print '<select name="RBCboard">'
    print '    <option value="RBC.2.1">RBC:12-1</option>'
    print '    <option value="RBC.2.2">RBC:2-3</option>'
    print '    <option value="RBC.2.3">RBC:4-5</option>'
    print '    <option value="RBC.2.4">RBC:6-7</option>'
    print '    <option value="RBC.2.5">RBC:8-9</option>'
    print '    <option value="RBC.2.6">RBC:10-11</option>'
    print '</select>'
    print '<input type=submit value="Configure" />'
    print '</p>'
    print ''
    print '</form>'

    print '<h4>Wheel +1: RBC Configuration</h4>'
    print ''
    print '<p>'
    print 'Select RBC board to configure:'
    print ''
    print '<form name="secform" action="http://localhost:5000/configure.rbc-cgi.py">'
    print '<select name="RBCboard">'
    print '    <option value="RBC.1.11">RBC:12-1</option>'
    print '    <option value="RBC.1.12">RBC:2-3</option>'
    print '    <option value="RBC.1.13">RBC:4-5</option>'
    print '    <option value="RBC.1.14">RBC:6-7</option>'
    print '    <option value="RBC.1.15">RBC:8-9</option>'
    print '    <option value="RBC.1.16">RBC:10-11</option>'
    print '</select>'
    print '<input type=submit value="Configure" />'
    print '</p>'
    print '</form>'
    
    print '<h4>Wheel +2: RBC Configuration</h4>'
    print ''
    print '<p>'
    print 'Select RBC board to configure:'
    print ''
    print '<form name="secform" action="http://localhost:5000/configure.rbc-cgi.py">'
    print '<select name="RBCboard">'
    print '    <option value="RBC.3.11">RBC:12-1</option>'
    print '    <option value="RBC.3.12">RBC:2-3</option>'
    print '    <option value="RBC.3.13">RBC:4-5</option>'
    print '    <option value="RBC.3.14">RBC:6-7</option>'
    print '    <option value="RBC.3.15">RBC:8-9</option>'
    print '    <option value="RBC.3.16">RBC:10-11</option>'
    print '</select>'
    print '<input type=submit value="Configure" />'
    print '</p>'
    print '</form>'

    #...
    print '</div>'
    print '</body>'
    print '</html>'
    
configure()

