//
// File generated by rootcint at Fri Nov  4 14:54:48 2011

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TDataSetsDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TDataSetsDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TDataSets_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TDataSets(void *p = 0);
   static void *newArray_TDataSets(Long_t size, void *p);
   static void delete_TDataSets(void *p);
   static void deleteArray_TDataSets(void *p);
   static void destruct_TDataSets(void *p);
   static void streamer_TDataSets(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TDataSets*)
   {
      ::TDataSets *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TDataSets >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TDataSets", ::TDataSets::Class_Version(), "./TDataSets.h", 24,
                  typeid(::TDataSets), DefineBehavior(ptr, ptr),
                  &::TDataSets::Dictionary, isa_proxy, 0,
                  sizeof(::TDataSets) );
      instance.SetNew(&new_TDataSets);
      instance.SetNewArray(&newArray_TDataSets);
      instance.SetDelete(&delete_TDataSets);
      instance.SetDeleteArray(&deleteArray_TDataSets);
      instance.SetDestructor(&destruct_TDataSets);
      instance.SetStreamerFunc(&streamer_TDataSets);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TDataSets*)
   {
      return GenerateInitInstanceLocal((::TDataSets*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TDataSets*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TDataSets::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TDataSets::Class_Name()
{
   return "TDataSets";
}

//______________________________________________________________________________
const char *TDataSets::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TDataSets*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TDataSets::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TDataSets*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TDataSets::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TDataSets*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TDataSets::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TDataSets*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TDataSets::Streamer(TBuffer &R__b)
{
   // Stream an object of class TDataSets.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> Id;
      { TString R__str; R__str.Streamer(R__b); name = R__str.Data(); }
      R__b >> graph;
      R__b.CheckByteCount(R__s, R__c, TDataSets::IsA());
   } else {
      R__c = R__b.WriteVersion(TDataSets::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << Id;
      { TString R__str = name.c_str(); R__str.Streamer(R__b);}
      R__b << graph;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TDataSets::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TDataSets.
      TClass *R__cl = ::TDataSets::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Id", &Id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "name", (void*)&name);
      R__insp.InspectMember("string", (void*)&name, "name.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*graph", &graph);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TDataSets(void *p) {
      return  p ? new(p) ::TDataSets : new ::TDataSets;
   }
   static void *newArray_TDataSets(Long_t nElements, void *p) {
      return p ? new(p) ::TDataSets[nElements] : new ::TDataSets[nElements];
   }
   // Wrapper around operator delete
   static void delete_TDataSets(void *p) {
      delete ((::TDataSets*)p);
   }
   static void deleteArray_TDataSets(void *p) {
      delete [] ((::TDataSets*)p);
   }
   static void destruct_TDataSets(void *p) {
      typedef ::TDataSets current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TDataSets(TBuffer &buf, void *obj) {
      ((::TDataSets*)obj)->::TDataSets::Streamer(buf);
   }
} // end of namespace ROOT for class ::TDataSets

/********************************************************
* TDataSetsDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTDataSetsDict();

extern "C" void G__set_cpp_environmentTDataSetsDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TDataSets.h");
  G__cpp_reset_tagtableTDataSetsDict();
}
#include <new>
extern "C" int G__cpp_dllrevTDataSetsDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TDataSets */
static int G__TDataSetsDict_517_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDataSets* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TDataSets[n];
     } else {
       p = new((void*) gvp) TDataSets[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TDataSets;
     } else {
       p = new((void*) gvp) TDataSets;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDataSets* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TDataSets((int) G__int(libp->para[0]), *(string*) libp->para[1].ref);
   } else {
     p = new((void*) gvp) TDataSets((int) G__int(libp->para[0]), *(string*) libp->para[1].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TDataSets*) G__getstructoffset())->getGraph());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDataSets*) G__getstructoffset())->setMarker((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TDataSets::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDataSets::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TDataSets::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TDataSets::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDataSets*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDataSets::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TDataSets::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDataSets::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDataSetsDict_517_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TDataSets::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TDataSetsDict_517_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TDataSets* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TDataSets(*(TDataSets*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TDataSets G__TTDataSets;
static int G__TDataSetsDict_517_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TDataSets*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TDataSets*) (soff+(sizeof(TDataSets)*i)))->~G__TTDataSets();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TDataSets*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TDataSets*) (soff))->~G__TTDataSets();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TDataSetsDict_517_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDataSets* dest = (TDataSets*) G__getstructoffset();
   *dest = *(TDataSets*) libp->para[0].ref;
   const TDataSets& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TDataSets */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTDataSetsDict {
 public:
  G__Sizep2memfuncTDataSetsDict(): p(&G__Sizep2memfuncTDataSetsDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTDataSetsDict::*p)();
};

size_t G__get_sizep2memfuncTDataSetsDict()
{
  G__Sizep2memfuncTDataSetsDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTDataSetsDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets))) {
     TDataSets *G__Lderived;
     G__Lderived=(TDataSets*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets),G__get_linked_tagnum(&G__TDataSetsDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTDataSetsDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TDataSetsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TDataSetsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TDataSetsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TDataSetsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TDataSetsDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TDataSets */
static void G__setup_memvarTDataSets(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets));
   { TDataSets *p; p=(TDataSets*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"Id=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDataSetsDictLN_string),-1,-1,4,"name=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TDataSetsDictLN_TGraphAsymmErrors),-1,-1,4,"graph=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TDataSetsDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTDataSetsDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTDataSets(void) {
   /* TDataSets */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets));
   G__memfunc_setup("TDataSets",877,G__TDataSetsDict_517_0_1, 105, G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TDataSets",877,G__TDataSetsDict_517_0_2, 105, G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets), -1, 0, 2, 1, 1, 0, 
"i - - 0 - id u 'string' - 1 - nm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getGraph",818,G__TDataSetsDict_517_0_3, 85, G__get_linked_tagnum(&G__TDataSetsDictLN_TGraphAsymmErrors), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMarker",942,G__TDataSetsDict_517_0_4, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - marker i - - 0 - colour "
"f - - 0 - size", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TDataSetsDict_517_0_5, 85, G__get_linked_tagnum(&G__TDataSetsDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TDataSets::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TDataSetsDict_517_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDataSets::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TDataSetsDict_517_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TDataSets::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TDataSetsDict_517_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TDataSets::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TDataSetsDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TDataSetsDict_517_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TDataSetsDict_517_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDataSets::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TDataSetsDict_517_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDataSets::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TDataSetsDict_517_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDataSets::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TDataSetsDict_517_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDataSets::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TDataSets", 877, G__TDataSetsDict_517_0_17, (int) ('i'), G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets), -1, 0, 1, 1, 1, 0, "u 'TDataSets' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TDataSets", 1003, G__TDataSetsDict_517_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TDataSetsDict_517_0_19, (int) ('u'), G__get_linked_tagnum(&G__TDataSetsDictLN_TDataSets), -1, 1, 1, 1, 1, 0, "u 'TDataSets' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTDataSetsDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTDataSetsDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTDataSetsDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TDataSetsDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TDataSetsDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_TGraphAsymmErrors = { "TGraphAsymmErrors" , 99 , -1 };
G__linked_taginfo G__TDataSetsDictLN_TDataSets = { "TDataSets" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTDataSetsDict() {
  G__TDataSetsDictLN_TClass.tagnum = -1 ;
  G__TDataSetsDictLN_TBuffer.tagnum = -1 ;
  G__TDataSetsDictLN_TMemberInspector.tagnum = -1 ;
  G__TDataSetsDictLN_TObject.tagnum = -1 ;
  G__TDataSetsDictLN_string.tagnum = -1 ;
  G__TDataSetsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TDataSetsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TDataSetsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TDataSetsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TDataSetsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TDataSetsDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TDataSetsDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TDataSetsDictLN_TGraphAsymmErrors.tagnum = -1 ;
  G__TDataSetsDictLN_TDataSets.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTDataSetsDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_string);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_TGraphAsymmErrors);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TDataSetsDictLN_TDataSets),sizeof(TDataSets),-1,62720,(char*)NULL,G__setup_memvarTDataSets,G__setup_memfuncTDataSets);
}
extern "C" void G__cpp_setupTDataSetsDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTDataSetsDict()");
  G__set_cpp_environmentTDataSetsDict();
  G__cpp_setup_tagtableTDataSetsDict();

  G__cpp_setup_inheritanceTDataSetsDict();

  G__cpp_setup_typetableTDataSetsDict();

  G__cpp_setup_memvarTDataSetsDict();

  G__cpp_setup_memfuncTDataSetsDict();
  G__cpp_setup_globalTDataSetsDict();
  G__cpp_setup_funcTDataSetsDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTDataSetsDict();
  return;
}
class G__cpp_setup_initTDataSetsDict {
  public:
    G__cpp_setup_initTDataSetsDict() { G__add_setup_func("TDataSetsDict",(G__incsetup)(&G__cpp_setupTDataSetsDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTDataSetsDict() { G__remove_setup_func("TDataSetsDict"); }
};
G__cpp_setup_initTDataSetsDict G__cpp_setup_initializerTDataSetsDict;

