/********************************************************************
* TDataSetsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TDataSetsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTDataSetsDict();
extern void G__cpp_setup_inheritanceTDataSetsDict();
extern void G__cpp_setup_typetableTDataSetsDict();
extern void G__cpp_setup_memvarTDataSetsDict();
extern void G__cpp_setup_globalTDataSetsDict();
extern void G__cpp_setup_memfuncTDataSetsDict();
extern void G__cpp_setup_funcTDataSetsDict();
extern void G__set_cpp_environmentTDataSetsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TDataSets.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TDataSetsDictLN_TClass;
extern G__linked_taginfo G__TDataSetsDictLN_TBuffer;
extern G__linked_taginfo G__TDataSetsDictLN_TMemberInspector;
extern G__linked_taginfo G__TDataSetsDictLN_TObject;
extern G__linked_taginfo G__TDataSetsDictLN_string;
extern G__linked_taginfo G__TDataSetsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TDataSetsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDataSetsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TDataSetsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDataSetsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TDataSetsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TDataSetsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TDataSetsDictLN_TGraphAsymmErrors;
extern G__linked_taginfo G__TDataSetsDictLN_TDataSets;

/* STUB derived class for protected member access */
