#!/bin/bash
cd ~/bin

xdaqappdir=/nfshome0/rpcdev/TriDAS/rpct/xdaqTtuConfig

##$XDAQ_ROOT/bin/xdaq.sh -h vmepcS2G18-13 -p 1976 -c $xdaqappdir/xml

##$XDAQ_ROOT/bin/xdaq.sh -h vmepcS2G18-13 -p 1976 -c $xdaqappdir/xml/xdaqTtuConfig.xml

$XDAQ_ROOT/bin/xdaq.sh -h vmepcS2G18-13 -p 1976 -c $xdaqappdir/XdaqLBoxAllTtuConfig.xml

